name: Keep Render Alive
on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Render Alive
        run: curl -s -o /dev/null -w "%{http_code}" https://myagent-backend.onrender.com/
